### ISSUE TITLE
Add support for ES6 using Babel 

### ISSUE THREAD

**Issue by thejameskyle** [yeoman/generator-chrome-extension#106]
I am happy to contibute a PR for this.

**Comment by ragingwind** [comment]
Sure why not

**Comment by arthurvr** [comment]
:+1:

**Comment by marvinosswald** [comment]
:+1:

**Comment by arandilopez** [comment]
:+1:

**Comment by arthurvr** [comment]
On the while, is it time to remove coffeescript support? We did the same at generator-webapp I believe.

**Comment by ragingwind** [comment]
@arthurvr yeah It's time to remove it

**Comment by addyosmani** [comment]
:+1:

**Comment by HaNdTriX** [comment]
:+1:

**Comment by l4u** [comment]
:+1: babel

**Comment by ragingwind** [comment]
@thejameskyle  any progress?

**Comment by jgodi** [comment]
Ya, I would love this. Any thoughts about gulp over grunt too?

**Comment by jeveloper** [comment]
babel +1

**Comment by brunoksato** [comment]
:+1:

**Comment by fantasywind** [comment]
+1 Babel

**Comment by arthurvr** [comment]
Personally I'd also prefer to switch to ESLint and switch to Gulp. It's the direction we've been going with some other generators too. Off topic in this ticket though. @ragingwind WDYT?

**Comment by ragingwind** [comment]
@arthurvr In personally, I like to move it to gulp and ESLint but I'm concerned that It makes the user confused without having to make a new generator like a generator-gulp-webapp

**Comment by arthurvr** [comment]
> In personally, I like to move it to gulp and ESLint but I'm concerned that It makes the user confused without having to make a new generator like a generator-gulp-webapp

Nah, why would that confuse people? I believe the reason there's a different generator for generator-gulp-webapp is more because it initially was an experiment, not really because it would confuse people. And the Grunt generator-webapp is soon going to be deprecated FYI. 

Could also go the way generator-angular went and have it as an option: https://github.com/yeoman/generator-angular/commit/9ad4d74f40b91b891712ddf44eb35c278d1ecb61 (I'd prefer not to, though).

**Comment by ragingwind** [comment]
Because there are some people who prefer to use grunt and I guess still want to use grunt. I assume that is one of the reason why angular generator have two options. Anyway, I don't like to support two build system in the generator as an option. :/ I bet gulp if the Grunt generator-webapp will be deprecated

**Comment by HaNdTriX** [comment]
@ragingwind & @arthurvr I have described my motivation why I created a separate project in [this issue](https://github.com/HaNdTriX/generator-chrome-extension-kickstart/issues/3).
